### ISSUE TITLE
Turtle Text Enlarges ad nauseum

### ISSUE THREAD

**Issue by mfong4151** [Marcoshenrich/fishtank#1]
When I click on a turtle the pop up screen enlarges the text per the effect you've put on, but it seems to get to a certain size, stop, and then go back down to the starting size.

**Comment by Marcoshenrich** [comment]
User is using a screen the size of a barn door, issue deprioritized as edge case.

**Comment by mfong4151** [comment]
loooooooooooooooollllllllllllllll
